CREATE TABLE BUSINESS_MASTER(ID INT, BUSINESS_AGE INT, TOTAL_EMPLOYEES DOUBLE, TURNOVER DOUBLE);
INSERT INTO BUSINESS_MASTER ( ID , BUSINESS_AGE , TOTAL_EMPLOYEES , TURNOVER ) VALUES ( 1,10,200.0,1000000.0);
create table PROPERTY_MASTER(ID INT, AGE INT, PROPERTY_VALUE DOUBLE);
insert into PROPERTY_MASTER values(1,10,100000);